version: '3.4'

services:
  selftodo.server:
    image: ${DOCKER_REGISTRY-}selftodoapi
    build:
      context: .
      dockerfile: SelfTodo.Server/Dockerfile

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: DBSelfTodo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
volumes:
  postgres-data: