version: '3.4'
networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - selftodo.server
      - selftodo.client
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - dev

  selftodo.server:
    image: ${DOCKER_REGISTRY-}selftodoapi
    build:
      context: .
      dockerfile: SelfTodo.Server/Dockerfile
    networks:
      - dev

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: DBSelfTodo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev

  selftodo.client:
    build:
      context: ./selftodo.client
    networks:
      - dev
  
volumes:
  postgres-data: